[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true

[theme]
base = "dark"
primaryColor = "#c6a577"
backgroundColor = "#14161b"
secondaryBackgroundColor = "#1c1f26"
textColor = "#f0f0ef"
font = "sans serif"
